if has("gui_macvim")

  set fuoptions=maxvert,maxhorz " fullscreen options (MacVim only), resized window when changed to fullscreen
  set guifont=Monospace:h8
  set guioptions-=T  " remove toolbar
  set guicursor=a:blinkon0

  " Unmap Apple+T and Shift+Apple+T
  macmenu &File.Open\ Tab\.\.\. key=<nop>

  " FuzzyFinder
  nnoremap <D-T> :FuzzyFinderTextMate<CR>

  " NerdTree
  nnoremap <D-e> :NERDTreeToggle<CR>

  " Tab navigation like FF and TM
  nnoremap <D-M-right> :tabnext<CR>
  nnoremap <D-M-left> :tabprev<CR>

elseif has("gui_gtk2")

  set guifont=Monospace\ 8
  set guioptions-=T        " remove toolbar
  set guioptions-=m        " remove menu

  nnoremap <A-e> :NERDTreeToggle<CR>
  nnoremap <A-t> :FuzzyFinderTextMate<CR>

elseif has("x11")
elseif has("gui_win32")
end

set anti " Antialias font

" Default size of window
set columns=170
set lines=90

" Tab headings
set gtl=%t gtt=%F
