call pathogen#runtime_append_all_bundles()

set tabstop=2
set shiftwidth=2
set showmatch
set autoindent
"set copyindent
set backspace=2
set smartindent
set smarttab
set incsearch
set hlsearch
set ruler
"set number
set laststatus=2

" disable file backups
set nobackup
set nowb
set noswapfile

colorscheme rdark

" reload when .vimrc is saved
autocmd! bufwritepost ~/.vimrc source ~/.vimrc
autocmd! bufwritepost vimrc source vimrc

autocmd FileType ruby setl expandtab
autocmd FileType haml setl expandtab
autocmd FileType sass setl expandtab
autocmd FileType scss setl expandtab
autocmd FileType coffee setl expandtab

autocmd BufNewFile,BufRead *.sass set filetype=sass
autocmd BufNewFile,BufRead *.scss set filetype=scss
autocmd BufNewFile,BufRead *.coffee set filetype=coffee
autocmd BufNewFile,BufRead Gemfile set filetype=ruby

nnoremap <C-w> :bd<CR>
nnoremap <C-Tab> :b#<CR>
nnoremap <C-t> :tabnew<CR>
nnoremap <A-1> :tabprev<CR>
nnoremap <A-2> :tabnext<CR>

