set tabstop=2
set shiftwidth=2
set showmatch
set autoindent
set copyindent
set smartindent
set incsearch
set hlsearch

" disable file backups
set nobackup
set nowb
set noswapfile

colorscheme slate

" reload when .vimrc is saved
autocmd! bufwritepost ~/.vimrc source ~/.vimrc
autocmd! bufwritepost vimrc source vimrc

autocmd FileType ruby setl expandtab
autocmd FileType haml setl expandtab

nnoremap <C-w> :bd<CR>
nnoremap <C-Tab> :b#<CR>
nnoremap <C-t> :tabnew<CR>
nnoremap <A-1> :tabprev<CR>
nnoremap <A-2> :tabnext<CR>
